### ISSUE TITLE
Mario is flying

### ISSUE THREAD

**Issue by mlemaudit** [BrentAureli/SuperMario#1]
If you hit the up key several times, Mario jumps repeatedly and consequently flies.

**Comment by mlemaudit** [comment]
Hello, the following patch should correct the issue :

Index: core/src/com/brentaureli/mariobros/Sprites/Mario.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- core/src/com/brentaureli/mariobros/Sprites/Mario.java	(date 1445566359000)
+++ core/src/com/brentaureli/mariobros/Sprites/Mario.java	(revision )
@@ -220,8 +220,10 @@
     }
 
     public void jump(){
+        if ( currentState != State.JUMPING ) { // to prevent mario from flying with infinite jumps // @SuperMario#1
-        b2body.applyLinearImpulse(new Vector2(0, 4f), b2body.getWorldCenter(), true);
-        currentState = State.JUMPING;
+            b2body.applyLinearImpulse(new Vector2(0, 4f), b2body.getWorldCenter(), true);
+            currentState = State.JUMPING;
+        } // @SuperMario#1
     }
 
     public void hit(Enemy enemy){

**Comment by BrentAureli** [comment]
fixed
